name: export-solution

on:
  workflow_dispatch:
    inputs:
      SolutionName:
        description: "Enter the SolutionName"
        required: true
      SolutionExportedFolder:
        description: "Folder to Export"
        required: true
        
